import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { SiteService } from "@/modules/site/site.service";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const dynamic = "force-dynamic";

export async function generateMetadata(): Promise<Metadata> {
  const siteService = new SiteService();
  const config = await siteService.getSiteConfig();

  return {
    title: config?.site_name || "Create Next App",
    description: config?.site_description || "Generated by create next app",
    icons: config?.logo_image ? { icon: config.logo_image } : undefined,
  };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const siteService = new SiteService();
  const config = await siteService.getSiteConfig();

  const themeColors = config ? {
    "--primary-color": config.primary_color,
    "--secondary-color": config.secondary_color,
    "--accent-color": config.accent_color,
  } as React.CSSProperties : {};

  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={themeColors}
      >
        {children}
        <Toaster position="top-center" richColors theme="dark" />
      </body>
    </html>
  );
}
